CREATE TABLE payment (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  payment_id VARCHAR(64) UNIQUE NOT NULL,
  user_id BIGINT NOT NULL,
  amount BIGINT NOT NULL,
  currency VARCHAR(3) NOT NULL,
  method VARCHAR(32),
  status VARCHAR(32) NOT NULL,
  metadata JSON,
  provider_id VARCHAR(64),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE idempotency_keys (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  key_value VARCHAR(128) UNIQUE NOT NULL,
  payment_id VARCHAR(64),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);